package il.cshaifasweng.OCSFMediatorExample.server.mapping;

import il.cshaifasweng.OCSFMediatorExample.entities.domain.Payment;
import il.cshaifasweng.OCSFMediatorExample.entities.messages.CheckOut.PaymentDTO;

public class PaymentMapper {

    public static Payment fromDTO(PaymentDTO dto) {
        if (dto == null) return null;

        Payment payment = new Payment();
        payment.setMethod(Payment.Method.CREDIT_CARD);
        payment.setStatus(Payment.Status.INITIATED);
        payment.setMaskedCardNumber(dto.getCardNumberMasked());
        payment.setCardHolderName(dto.getCardHolderName());
        payment.setExpirationDate(dto.getExpirationDate());
        payment.setIdNumber(dto.getIdNumber());
        payment.setAmount(dto.getAmount());

        // Authorization code generated by server later if payment captured
        payment.setAuthCode(null);

        return payment;
    }

    public static PaymentDTO toDTO(Payment entity) {
        if (entity == null) return null;

        PaymentDTO dto = new PaymentDTO();
        dto.setCardNumberMasked(entity.getMaskedCardNumber());
        dto.setCardHolderName(entity.getCardHolderName());
        dto.setExpirationDate(entity.getExpirationDate());
        dto.setIdNumber(entity.getIdNumber());
        dto.setAmount(entity.getAmount());
        return dto;
    }
}