USE flowershop;

CREATE TABLE IF NOT EXISTS customers (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
email VARCHAR(254) NOT NULL,
password_hash CHAR(64) NOT NULL,
display_name VARCHAR(120) NOT NULL,
phone VARCHAR(32),
is_active BOOLEAN NOT NULL DEFAULT TRUE,
created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
CONSTRAINT uk_customers_email UNIQUE (email)
);
